#!/usr/bin/env bash
# congigure nginx on port 80 return hello world

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y

# starting nginx services
sudo service nginx start

# starting nginx service
sudo ufw allow 'Nginx HTTP'

# give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
}"

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
