#!/usr/bin/env bash

STUDENT_ID="92997"
WEB_01_IP="54.210.52.229"
WEB_02_IP="18.209.223.67"

# Install HAProxy
apt-get update
apt-get install -y haproxy

# Configure HAProxy
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server $STUDENT_ID-web-01 $WEB_01_IP:80 check
    server $STUDENT_ID-web-02 $WEB_02_IP:80 check
EOF

# Enable HAProxy init script
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
service haproxy restart
