#!/usr/bin/env bash
# this script dispplay ti infininty and beyound indefinitely
# With a sleep 2 in inbetween each item
# Display i am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
