#!/usr/bin/env bash
# This Bash Displays the content of the file /etc/passwd
# Script displays username, user id, home directory path for the user

myfile="/etc/passwd"
while IFS= read -r line
do
	echo "$line" | cut -d":" -f1,3,6
done < "$myfile"
