#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
#+ using the while loop + IFS
# USENAME, GROUP_ID, HOME_DIRECTORY, COMMAND/SHELL, PASSWORD, USER ID INFO

myfile="/etc/passwd"
f1=""
f2=""
f3=""
while IFS= read -r line
do
    f1="$(echo "$line" | cut -d":" -f1)"
    f2="$(echo "$line" | cut -d":" -f2)"
    f3="$(echo "$line" | cut -d":" -f3)"
    f4="$(echo "$line" | cut -d":" -f4)"
    f5="$(echo "$line" | cut -d":" -f5)"
    f6="$(echo "$line" | cut -d":" -f6)"
    f7="$(echo "$line" | cut -d":" -f7)"
    echo "The user ${f1} is part of the ${f4} gang, lives in ${f6} and rides ${f7}. ${f3}'s place is protected by the passcode ${f2}, more info about the user here: ${f5}"
done < "$myfile"
