#!/usr/bin/env bash
# This script displays information about the file 'school'

if [ -e "$school" ]
then
	echo "school file exists"
fi
if [ ! -f "$school" ]
then
	echo "school file does not exist"
if [ -z "$(cat "$school")" ]
then
	echo "school file is empty"
fi
elif [ "$(wc -l < "$school")" -eq 0 ]
then
	echo "school file is not empty"
fi
if [ -f "$school" ]
then
	echo "school is a regular file"
	fi
