#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
cp /etv/host ~/hosts.new
sed -i "s/^172[0-9]*\slocalhost/127.0.0.2 localost/" ~/hosts.new
sed -i "$ a\8.8.8.8 facebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
