#!/usr/bin/env bash
# This script changes the IP address resolution for localhost and facebook.com

# Change localhost resolution to 127.0.0.2
cp /etc/hosts ~/hosts.new
sed -i "s/^127[0-9.]*\slocalhost/127.0.0.2 localhost/" ~/hosts.new
# Change facebook.com resolution
sed -i "$ a\8.8.8.8 facebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
