#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine

# Use ifconfig to display active network interfaces and their IPs
ifconfig | grep -oP 'inet \K\S+' | grep -E '^(\d{1,3}\.){3}\d{1,3}$'

